### ISSUE TITLE
got error when running the code

### ISSUE THREAD

**Issue by weichenma15** [wufan-cse/gnas#1]
**/gnas-main/mmdet/models/roi_heads/nas_bbox_heads/cell_fc_bbox_head.py", line 50, in __init__
    super().__init__(*args, init_cfg=init_cfg, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'num_cls_cells'**

thanks for your contributions to open sourcing the code.
i just download this repo and change the dataset_root. Is this my problem or something else?

**Comment by Lybnn** [comment]
I also got the same error, how did you fix it please? Thanks

**Comment by l412198735** [comment]
I got the same error.

**Comment by wufan-cse** [comment]
The bug is fixed. Thank you.
