### ISSUE TITLE
A  question about Loss is Non

### ISSUE THREAD

**Issue by Lybnn** [wufan-cse/gnas#2]
Hi Author, When I am reproducing your code, the Loss is Non.How can I solve this problem?
In the search phase is shown below:
2024/05/07 10:49:36 - mmengine - INFO - Epoch(train)  [1][  50/4849]  lr: 1.9820e-03  eta: 1 day, 9:51:56  time: 2.0970  data_time: 0.0120  memory: 9219  loss: 2.7391  loss_rpn_cls: 0.5940  loss_rpn_bbox: 0.1222  loss_cls: 1.9735  acc: 93.7988  loss_bbox: 0.0494
2024/05/07 10:50:56 - mmengine - INFO - Epoch(train)  [1][ 100/4849]  lr: 3.9840e-03  eta: 1 day, 5:53:08  time: 1.6073  data_time: 0.0076  memory: 9219  loss: 1.9536  loss_rpn_cls: 0.2089  loss_rpn_bbox: 0.1173  loss_cls: 1.4533  acc: 88.6719  loss_bbox: 0.1740
2024/05/07 10:52:15 - mmengine - INFO - Epoch(train)  [1][ 150/4849]  lr: 5.9860e-03  eta: 1 day, 4:23:52  time: 1.5801  data_time: 0.0073  memory: 9219  loss: 1.6952  loss_rpn_cls: 0.1471  loss_rpn_bbox: 0.1102  loss_cls: 1.1002  acc: 81.5918  loss_bbox: 0.3377
2024/05/07 10:53:34 - mmengine - INFO - Epoch(train)  [1][ 200/4849]  lr: 7.9880e-03  eta: 1 day, 3:40:49  time: 1.5894  data_time: 0.0075  memory: 9219  loss: 1.8736  loss_rpn_cls: 0.1098  loss_rpn_bbox: 0.1168  loss_cls: 1.0912  acc: 76.5625  loss_bbox: 0.5558
2024/05/07 10:54:53 - mmengine - INFO - Epoch(train)  [1][ 250/4849]  lr: 9.9900e-03  eta: 1 day, 3:12:39  time: 1.5800  data_time: 0.0073  memory: 9219  loss: 1.8169  loss_rpn_cls: 0.1634  loss_rpn_bbox: 0.1067  loss_cls: 1.0662  acc: 90.7715  loss_bbox: 0.4807
2024/05/07 10:56:13 - mmengine - INFO - Epoch(train)  [1][ 300/4849]  lr: 1.1992e-02  eta: 1 day, 2:55:01  time: 1.5899  data_time: 0.0073  memory: 9219  loss: 1.7710  loss_rpn_cls: 0.2443  loss_rpn_bbox: 0.1356  loss_cls: 1.0330  acc: 87.5488  loss_bbox: 0.3581
2024/05/07 10:57:32 - mmengine - INFO - Epoch(train)  [1][ 350/4849]  lr: 1.3994e-02  eta: 1 day, 2:41:00  time: 1.5823  data_time: 0.0071  memory: 9219  loss: 1.8193  loss_rpn_cls: 0.2053  loss_rpn_bbox: 0.1216  loss_cls: 1.0617  acc: 94.2871  loss_bbox: 0.4307
2024/05/07 10:58:51 - mmengine - INFO - Epoch(train)  [1][ 400/4849]  lr: 1.5996e-02  eta: 1 day, 2:30:05  time: 1.5817  data_time: 0.0072  memory: 9219  loss: 1.7257  loss_rpn_cls: 0.2208  loss_rpn_bbox: 0.1258  loss_cls: 1.0209  acc: 91.8457  loss_bbox: 0.3582
2024/05/07 10:59:46 - mmengine - INFO - Epoch(train)  [1][ 450/4849]  lr: 1.7998e-02  eta: 1 day, 1:29:32  time: 1.0975  data_time: 0.0069  memory: 9219  loss: nan  loss_rpn_cls: nan  loss_rpn_bbox: nan  loss_cls: nan  acc: 0.0000  loss_bbox: nan
2024/05/07 11:00:36 - mmengine - INFO - Epoch(train)  [1][ 500/4849]  lr: 2.0000e-02  eta: 1 day, 0:30:48  time: 0.9925  data_time: 0.0073  memory: 5950  loss: nan  loss_rpn_cls: nan  loss_rpn_bbox: nan  loss_cls: nan  acc: 0.0000  loss_bbox: nan
In the augment phase it is as follows:
2024/05/08 09:08:21 - mmengine - INFO - Epoch(train)  [1][  50/4849]  lr: 1.9820e-03  eta: 7:27:32  time: 0.4619  data_time: 0.0096  memory: 9765  loss: 1.9158  loss_rpn_cls: 0.5695  loss_rpn_bbox: 0.1301  loss_cls: 1.1724  acc: 92.0898  loss_bbox: 0.0438
2024/05/08 09:08:43 - mmengine - INFO - Epoch(train)  [1][ 100/4849]  lr: 3.9840e-03  eta: 7:14:50  time: 0.4364  data_time: 0.0057  memory: 9764  loss: 1.5310  loss_rpn_cls: 0.1933  loss_rpn_bbox: 0.1193  loss_cls: 1.0172  acc: 84.0820  loss_bbox: 0.2012
2024/05/08 09:09:05 - mmengine - INFO - Epoch(train)  [1][ 150/4849]  lr: 5.9860e-03  eta: 7:08:00  time: 0.4291  data_time: 0.0058  memory: 9764  loss: 1.9189  loss_rpn_cls: 0.1332  loss_rpn_bbox: 0.1185  loss_cls: 1.1402  acc: 78.5156  loss_bbox: 0.5271
2024/05/08 09:09:27 - mmengine - INFO - Epoch(train)  [1][ 200/4849]  lr: 7.9880e-03  eta: 7:10:19  time: 0.4536  data_time: 0.0055  memory: 9764  loss: 1.9713  loss_rpn_cls: 0.1362  loss_rpn_bbox: 0.1162  loss_cls: 1.1502  acc: 89.8926  loss_bbox: 0.5687
2024/05/08 09:09:50 - mmengine - INFO - Epoch(train)  [1][ 250/4849]  lr: 9.9900e-03  eta: 7:12:00  time: 0.4559  data_time: 0.0057  memory: 9764  loss: 1.9821  loss_rpn_cls: 0.1435  loss_rpn_bbox: 0.1137  loss_cls: 1.1260  acc: 92.9688  loss_bbox: 0.5990
2024/05/08 09:10:12 - mmengine - INFO - Epoch(train)  [1][ 300/4849]  lr: 1.1992e-02  eta: 7:11:25  time: 0.4460  data_time: 0.0057  memory: 9764  loss: nan  loss_rpn_cls: nan  loss_rpn_bbox: nan  loss_cls: nan  acc: 1.0638  loss_bbox: nan
2024/05/08 09:10:32 - mmengine - INFO - Epoch(train)  [1][ 350/4849]  lr: 1.3994e-02  eta: 7:04:26  time: 0.3992  data_time: 0.0059  memory: 9764  loss: nan  loss_rpn_cls: nan  loss_rpn_bbox: nan  loss_cls: nan  acc: 7.3171  loss_bbox: nan

**Comment by wufan-cse** [comment]
The original search code works well in a single 4090 GPU and the log is as follows:
```
2024/05/06 22:29:26 - mmengine - INFO - Epoch(train)  [1][  50/4849]  lr: 1.9820e-03  eta: 8:06:20  time: 0.5019  data_time: 0.0154  memory: 9466  loss: 2.7694  loss_rpn_cls: 0.6222  loss_rpn_bbox: 0.1258  loss_cls: 1.9705  acc: 86.4258  loss_bbox: 0.0510
2024/05/06 22:29:50 - mmengine - INFO - Epoch(train)  [1][ 100/4849]  lr: 3.9840e-03  eta: 7:53:58  time: 0.4772  data_time: 0.0089  memory: 9466  loss: 1.9688  loss_rpn_cls: 0.2060  loss_rpn_bbox: 0.1154  loss_cls: 1.4562  acc: 84.9609  loss_bbox: 0.1913
2024/05/06 22:30:14 - mmengine - INFO - Epoch(train)  [1][ 150/4849]  lr: 5.9860e-03  eta: 7:48:49  time: 0.4748  data_time: 0.0087  memory: 9466  loss: 1.8111  loss_rpn_cls: 0.1423  loss_rpn_bbox: 0.1272  loss_cls: 1.1297  acc: 88.6719  loss_bbox: 0.4119
2024/05/06 22:30:38 - mmengine - INFO - Epoch(train)  [1][ 200/4849]  lr: 7.9880e-03  eta: 7:50:55  time: 0.4950  data_time: 0.0094  memory: 9466  loss: 1.8180  loss_rpn_cls: 0.1054  loss_rpn_bbox: 0.1054  loss_cls: 1.0722  acc: 80.4688  loss_bbox: 0.5350
...
2024/05/06 22:34:16 - mmengine - INFO - Epoch(train)  [1][ 650/4849]  lr: 2.0000e-02  eta: 7:44:14  time: 0.4735  data_time: 0.0069  memory: 9466  loss: 1.7961  loss_rpn_cls: 0.1159  loss_rpn_bbox: 0.0986  loss_cls: 1.0616  acc: 86.9141  loss_bbox: 0.5201
2024/05/06 22:34:40 - mmengine - INFO - Epoch(train)  [1][ 700/4849]  lr: 2.0000e-02  eta: 7:43:58  time: 0.4860  data_time: 0.0080  memory: 9466  loss: 1.7330  loss_rpn_cls: 0.1004  loss_rpn_bbox: 0.0962  loss_cls: 1.0512  acc: 88.3789  loss_bbox: 0.4851
2024/05/06 22:35:03 - mmengine - INFO - Epoch(train)  [1][ 750/4849]  lr: 2.0000e-02  eta: 7:42:45  time: 0.4715  data_time: 0.0084  memory: 9466  loss: 1.7215  loss_rpn_cls: 0.0824  loss_rpn_bbox: 0.0961  loss_cls: 1.0551  acc: 86.1816  loss_bbox: 0.4878
2024/05/06 22:35:28 - mmengine - INFO - Epoch(train)  [1][ 800/4849]  lr: 2.0000e-02  eta: 7:42:33  time: 0.4869  data_time: 0.0090  memory: 9466  loss: 1.7262  loss_rpn_cls: 0.0829  loss_rpn_bbox: 0.0859  loss_cls: 1.0609  acc: 84.3750  loss_bbox: 0.4966
2024/05/06 22:35:53 - mmengine - INFO - Epoch(train)  [1][ 850/4849]  lr: 2.0000e-02  eta: 7:42:56  time: 0.4975  data_time: 0.0094  memory: 9466  loss: 1.7825  loss_rpn_cls: 0.0919  loss_rpn_bbox: 0.0945  loss_cls: 1.0655  acc: 86.1328  loss_bbox: 0.5306
2024/05/06 22:36:17 - mmengine - INFO - Epoch(train)  [1][ 900/4849]  lr: 2.0000e-02  eta: 7:42:39  time: 0.4867  data_time: 0.0089  memory: 9466  loss: 1.7114  loss_rpn_cls: 0.1128  loss_rpn_bbox: 0.0944  loss_cls: 1.0467  acc: 88.3789  loss_bbox: 0.4575
2024/05/06 22:36:43 - mmengine - INFO - Epoch(train)  [1][ 950/4849]  lr: 2.0000e-02  eta: 7:44:18  time: 0.5254  data_time: 0.0103  memory: 9466  loss: 1.5919  loss_rpn_cls: 0.0695  loss_rpn_bbox: 0.0715  loss_cls: 1.0323  acc: 91.2598  loss_bbox: 0.4187
...
2024/05/06 23:05:03 - mmengine - INFO - Epoch(train)  [1][4400/4849]  lr: 2.0000e-02  eta: 7:20:29  time: 0.5082  data_time: 0.0097  memory: 9466  loss: 1.4277  loss_rpn_cls: 0.0350  loss_rpn_bbox: 0.0572  loss_cls: 0.9726  acc: 91.6992  loss_bbox: 0.3629
2024/05/06 23:05:27 - mmengine - INFO - Epoch(train)  [1][4450/4849]  lr: 2.0000e-02  eta: 7:20:00  time: 0.4837  data_time: 0.0087  memory: 9466  loss: 1.4512  loss_rpn_cls: 0.0327  loss_rpn_bbox: 0.0598  loss_cls: 0.9900  acc: 90.7227  loss_bbox: 0.3686
2024/05/06 23:05:51 - mmengine - INFO - Epoch(train)  [1][4500/4849]  lr: 2.0000e-02  eta: 7:19:29  time: 0.4800  data_time: 0.0080  memory: 9466  loss: 1.4521  loss_rpn_cls: 0.0353  loss_rpn_bbox: 0.0614  loss_cls: 0.9908  acc: 94.8730  loss_bbox: 0.3646
2024/05/06 23:06:16 - mmengine - INFO - Epoch(train)  [1][4550/4849]  lr: 2.0000e-02  eta: 7:19:07  time: 0.4950  data_time: 0.0090  memory: 9466  loss: 1.4381  loss_rpn_cls: 0.0481  loss_rpn_bbox: 0.0584  loss_cls: 0.9690  acc: 91.8457  loss_bbox: 0.3626
2024/05/06 23:06:42 - mmengine - INFO - Epoch(train)  [1][4600/4849]  lr: 2.0000e-02  eta: 7:19:02  time: 0.5251  data_time: 0.0110  memory: 9466  loss: 1.4348  loss_rpn_cls: 0.0369  loss_rpn_bbox: 0.0596  loss_cls: 0.9751  acc: 92.6758  loss_bbox: 0.3632
2024/05/06 23:07:09 - mmengine - INFO - Epoch(train)  [1][4650/4849]  lr: 2.0000e-02  eta: 7:18:58  time: 0.5272  data_time: 0.0112  memory: 9466  loss: 1.4243  loss_rpn_cls: 0.0352  loss_rpn_bbox: 0.0582  loss_cls: 0.9761  acc: 94.7266  loss_bbox: 0.3547
2024/05/06 23:07:33 - mmengine - INFO - Epoch(train)  [1][4700/4849]  lr: 2.0000e-02  eta: 7:18:31  time: 0.4882  data_time: 0.0090  memory: 9466  loss: 1.4316  loss_rpn_cls: 0.0381  loss_rpn_bbox: 0.0561  loss_cls: 0.9760  acc: 91.9922  loss_bbox: 0.3613
2024/05/06 23:07:57 - mmengine - INFO - Epoch(train)  [1][4750/4849]  lr: 2.0000e-02  eta: 7:18:01  time: 0.4823  data_time: 0.0085  memory: 9466  loss: 1.4501  loss_rpn_cls: 0.0343  loss_rpn_bbox: 0.0606  loss_cls: 0.9822  acc: 93.1152  loss_bbox: 0.3730
2024/05/06 23:08:21 - mmengine - INFO - Epoch(train)  [1][4800/4849]  lr: 2.0000e-02  eta: 7:17:32  time: 0.4837  data_time: 0.0086  memory: 9466  loss: 1.4383  loss_rpn_cls: 0.0385  loss_rpn_bbox: 0.0645  loss_cls: 0.9800  acc: 91.1133  loss_bbox: 0.3554
```
Here are some suggestions to solve the nan loss:
```
1. Try to restart the code.
2. Use a lower learning rate.
3. Use a larger warm_up step, for example, change the 'end' of 'LinearLR' in 'configs/__base__/schedule_1x.py' to 2000.
```
Thank you.

**Comment by Lybnn** [comment]
I see,I tried your suggestion and solved the problem.Thank you.
