### ISSUE TITLE
The mAP results are not that good

### ISSUE THREAD

**Issue by fang-lg** [wufan-cse/gnas#3]
Hello, I will follow your method for the search phase first, followed by the enhancement phase. However, the results of the enhancement phase are not as good, with only 50.6 mAP, which is far from the 58.4 mentioned in your paper

class     | gts   | dets   | recall | ap    |
+-----------+-------+--------+--------+-------+
| aeroplane | 1738  | 94153  | 0.861  | 0.463 |
| bicycle   | 1046  | 79408  | 0.714  | 0.400 |
| bird      | 95339 | 230954 | 0.820  | 0.748 |
| boat      | 537   | 76612  | 0.685  | 0.298 |
| bottle    | 12309 | 107673 | 0.741  | 0.594 |
| bus       | 787   | 79871  | 0.764  | 0.467 |
| car       | 5029  | 117842 | 0.884  | 0.569 |
+-----------+-------+--------+--------+-------+
| mAP       |       |        |        | 0.506

**Comment by Xingjie-Han** [comment]
Hello, may I ask why the class category displayed in the final result is different from the CLASSES parameter in the gnas_search_faster rcnn_r101_fpn_1x_coco. py file

**Comment by wufan-cse** [comment]
@fang-lg Sorry for the late response. The process for releasing the official checkpoint is in process. Meanwhile, an informal checkpoint with 57.6 mAP on Daytime-Sunny can be found in https://huggingface.co/fffan/gnas. Thank you.

**Comment by Xingjie-Han** [comment]
您的来信已收到。

**Comment by wufan-cse** [comment]
@Xingjie-Han Although the displayed classes are different, the quantitative results are correct for each class. You can check mmdetection documents for further instructions to solve this problem. Thank you.

**Comment by coleson-CL** [comment]
> Hello, I will follow your method for the search phase first, followed by the enhancement phase. However, the results of the enhancement phase are not as good, with only 50.6 mAP, which is far from the 58.4 mentioned in your paper你好，我将按照你的方法先进行搜索阶段，然后是增强阶段。然而，增强阶段的结果就不那么好了，mAP只有50.6，与您文章中提到的58.4相差甚远
> 
> class | gts | dets | recall | ap |Class | GTS | dets | recall | ap | +-----------+-------+--------+--------+-------+ ----------- ------- -------- -------- ------- | aeroplane | 1738 | 94153 | 0.861 | 0.463 ||飞机| 1738 | 94153 | 0.861 | 0.463 | | bicycle | 1046 | 79408 | 0.714 | 0.400 ||自行车| 1046 | 79408 | 0.714 | 0.400 | | bird | 95339 | 230954 | 0.820 | 0.748 ||鸟| 95339 | 230954 | 0.820 | 0.748 | | boat | 537 | 76612 | 0.685 | 0.298 ||小艇| 537 | 76612 | 0.685 | 0.298 | | bottle | 12309 | 107673 | 0.741 | 0.594 ||瓶| 12309 | 107673 | 0.741 | 0.594 | | bus | 787 | 79871 | 0.764 | 0.467 ||总线| 787 | 79871 | 0.764 | 0.467 | | car | 5029 | 117842 | 0.884 | 0.569 | +-----------+-------+--------+--------+-------+ ----------- ------- -------- -------- ------- | mAP | | | | 0.506

What is the command used in the test?

**Comment by Xingjie-Han** [comment]
您的来信已收到。
