### ISSUE TITLE
About generalization metrics on other data

### ISSUE THREAD

**Issue by ZhenxiongTang** [wufan-cse/gnas#7]
首先感谢您的贡献，我有一些疑问。首先，我从其他已经关闭的问题里看到，你整个过程使用的是单个4090是吗，不知是否因为设备原因，我在增强阶段也出现了nan的问题，所以初始学习率进行了一些调整，我在源域复现过程中也只能达到51。其次是，在其他目标域中的mAP是怎么实现的？我是直接将增强阶段的数据集路径更改成目标域的了，不知是否理解正确了。期待您的回复。

**Comment by wufan-cse** [comment]
你好，感谢提问。
1. ‘’增强阶段也出现了nan的问题‘’
答：整个过程是使用单个4090，Nan问题的解决可以参考 #2 ，另外G-loss的回归部分可能是导致loss不稳定的因素，可以尝试调小（或设置为0）loss_bbox中的penalty_weight来训练以及debug。

2. ‘’源域复现过程中也只能达到51‘’
答：有非正式的开源权重，源域mAP为57.6，参考 #3 

3. ‘’其他目标域中的mAP是怎么实现的‘’
答：其他目标域直接加载源域训练好的权重并运行测试代码，无需重新训练，您的理解没有错。
